Repository LukaLai/ProjectDevops, pull requests merged in 2024-04, with the labels that each got.

#4 feat(gitignore): adding gitignore to avoid .idea to be pushed
  .gitignore
  .idea/.gitignore
  .idea/ProjectDevops.iml
  .idea/modules.xml
  .idea/vcs.xml
Labels: enhancement

#9 ci(Vercel): Add vercel deployment
  .github/workflows/lint.yml
  .github/workflows/vercel.yml
  vercel.json
Labels: enhancement

#13 test(tests): adding test config for jest and a unit test for page.jsx
  .github/workflows/tests.yml
  __tests__/page.test.jsx
  jest.config.ts
  package-lock.json
  package.json
Labels: enhancement

#15 test(snapshots): adding snapshot tests
  __tests__/snapshots/__snapshots__/alert-snapshot.js.snap
  __tests__/snapshots/__snapshots__/avatar-snapshot.js.snap
  __tests__/snapshots/__snapshots__/container-snapshot.js.snap
  __tests__/snapshots/__snapshots__/cover-image-snapshot.js.snap
  __tests__/snapshots/__snapshots__/date-formatter-snapshot.js.snap
  __tests__/snapshots/__snapshots__/footer-snapshot.js.snap
  __tests__/snapshots/__snapshots__/header-snapshot.js.snap
  __tests__/snapshots/__snapshots__/hero-post-snapshot.js.snap
  __tests__/snapshots/__snapshots__/intro-snapshot.js.snap
  __tests__/snapshots/__snapshots__/more-stories-snapshot.js.snap
  __tests__/snapshots/__snapshots__/page-snapshot.js.snap
  __tests__/snapshots/__snapshots__/post-body-snapshot.js.snap
  __tests__/snapshots/__snapshots__/post-header-snapshot.js.snap
  __tests__/snapshots/__snapshots__/post-preview-snapshot.js.snap
  __tests__/snapshots/__snapshots__/post-title-snapshot.js.snap
  __tests__/snapshots/__snapshots__/section-snapshot.js.snap
  __tests__/snapshots/alert-snapshot.js
  __tests__/snapshots/avatar-snapshot.js
  __tests__/snapshots/container-snapshot.js
  __tests__/snapshots/cover-image-snapshot.js
  __tests__/snapshots/date-formatter-snapshot.js
  __tests__/snapshots/footer-snapshot.js
  __tests__/snapshots/header-snapshot.js
  __tests__/snapshots/hero-post-snapshot.js
  __tests__/snapshots/intro-snapshot.js
  __tests__/snapshots/more-stories-snapshot.js
  __tests__/snapshots/page-snapshot.js
  __tests__/snapshots/post-body-snapshot.js
  __tests__/snapshots/post-header-snapshot.js
  __tests__/snapshots/post-preview-snapshot.js
  __tests__/snapshots/post-title-snapshot.js
  __tests__/snapshots/section-snapshot.js
  __tests__/unit_tests/page.test.jsx
Labels: enhancement

#18 Adding a unit test and a snapshot test
  __tests__/snapshots/_components/__snapshots__/alert-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/avatar-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/container-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/cover-image-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/date-formatter-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/footer-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/header-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/hero-post-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/intro-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/more-stories-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/post-body-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/post-header-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/post-preview-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/post-title-snapshot.js.snap
  __tests__/snapshots/_components/__snapshots__/section-snapshot.js.snap
  __tests__/snapshots/_components/alert-snapshot.js
  __tests__/snapshots/_components/avatar-snapshot.js
  __tests__/snapshots/_components/container-snapshot.js
  __tests__/snapshots/_components/cover-image-snapshot.js
  __tests__/snapshots/_components/date-formatter-snapshot.js
  __tests__/snapshots/_components/footer-snapshot.js
  __tests__/snapshots/_components/header-snapshot.js
  __tests__/snapshots/_components/hero-post-snapshot.js
  __tests__/snapshots/_components/intro-snapshot.js
  __tests__/snapshots/_components/more-stories-snapshot.js
  __tests__/snapshots/_components/post-body-snapshot.js
  __tests__/snapshots/_components/post-header-snapshot.js
  __tests__/snapshots/_components/post-preview-snapshot.js
  __tests__/snapshots/_components/post-title-snapshot.js
  __tests__/snapshots/_components/section-snapshot.js
  __tests__/unit_tests/_components/alert.test.jsx
  src/app/layout.tsx
Labels: enhancement

#20 feat:add package speed-insights-vercel
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: enhancement

#22 docs(readme): Adding documentation about project, ci, monitoring and workflow
  README.md
  docs/img/image-1.png
  docs/img/image-2.png
  docs/img/image.png
Labels: documentation

#24 fix(layout.tsx): fixed layout not rendering properly
  src/app/layout.tsx
Labels: bug
